# Generated by Django 4.1.7 on 2023-04-02 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "login",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("groupName", models.CharField(max_length=100)),
                ("contactPersonName", models.CharField(default="", max_length=100)),
                ("contactPersonEmail", models.EmailField(default="", max_length=254)),
                ("contactPersonPhone", models.CharField(default="", max_length=100)),
                ("amountOfPeople", models.IntegerField()),
                ("limitedMobility", models.BooleanField(default=False)),
                ("isSchool", models.BooleanField(default=False)),
                ("onderwijsNiveau", models.CharField(blank=True, max_length=100)),
                ("studieJaar", models.CharField(blank=True, max_length=100)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "assignedGuide",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MyPlanner.guide",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MyPlanner.module",
                    ),
                ),
            ],
        ),
    ]
