# Generated by Django 4.1.7 on 2023-04-03 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("MyPlanner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupvisit",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="module",
            name="description",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
