# Generated by Django 4.1.7 on 2023-04-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyPlanner", "0002_groupvisit_created_at_alter_module_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupvisit",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
