# Generated by Django 4.1.7 on 2023-04-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyPlanner", "0003_groupvisit_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupvisit",
            name="lunch_vooruitzicht",
            field=models.BooleanField(default=True),
        ),
    ]
