# Generated by Django 4.1.7 on 2023-04-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPlanner', '0004_groupvisit_lunch_vooruitzicht'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupvisit',
            name='leeftijdStudent',
            field=models.IntegerField(default=0),
        ),
    ]
