# Generated by Django 4.1.7 on 2023-04-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPlanner', '0005_groupvisit_leeftijdstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupvisit',
            name='leeftijdStudent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
